---
name: frontend CI pipeline
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ##############################
      # checkout
      ##############################
    - name: checkout code
      uses: actions/checkout@v4

      ##############################
      #Docker login
      ##############################
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
      ##############################
      # Build
      ##############################
    - name: Build
      run:
        docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/vst-homepage-frontend:${{ github.run_number }} \
          -t ${{ secrets.DOCKER_USERNAME }}/vst-homepage-frontend:latest \
      ##############################
      # Push
      ##############################
    - name: Push
      run: 
        docker push ${{ secrets.DOCKER_USERNAME }}/vst-homepage-frontend:${{ github.run_number }} \
        docker push ${{ secrets.DOCKER_USERNAME }}/vst-homepage-frontend:latest